### ISSUE TITLE
NoRefresh doesn't work on new firmware 1.2.0

### ISSUE THREAD

**Issue by eneq123** [marcelogp/NoRefreshToggle#2]
NoRefresh Settings force close on checking "Current Service State" box. And NoRefresh doesn't start.

**Comment by marcelogp** [comment]
I'm not using firmware 1.2.0 (what's new on this version, anyway?), so it would be easier if you provide a crash log for me to analyze. You can do that by running "adb logcat" and copying the section related to the crash.

**Comment by eneq123** [comment]
11-25 13:33:00.861 W/dalvikvm(1897)threadid=3: thread exiting with uncaught exception (group=0x4001b170)
11-25 13:33:00.861 E/AndroidRuntime(1897)Uncaught handler: thread main exiting due to uncaught exception
11-25 13:33:00.868 E/AndroidRuntime(1897)java.lang.NoSuchMethodError: android.hardware.EpdController.setRegion
11-25 13:33:00.868 E/AndroidRuntime(1897)at com.eink.norefresh.A2Service.setEpdNormal(A2Service.java:267)
11-25 13:33:00.868 E/AndroidRuntime(1897)at com.eink.norefresh.A2Service.onStartCommand(A2Service.java:232)
11-25 13:33:00.868 E/AndroidRuntime(1897)at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2873)
11-25 13:33:00.868 E/AndroidRuntime(1897)at android.app.ActivityThread.access$3500(ActivityThread.java:119)
11-25 13:33:00.868 E/AndroidRuntime(1897)at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
11-25 13:33:00.868 E/AndroidRuntime(1897)at android.os.Handler.dispatchMessage(Handler.java:99)
11-25 13:33:00.868 E/AndroidRuntime(1897)at android.os.Looper.loop(Looper.java:123)
11-25 13:33:00.868 E/AndroidRuntime(1897)at android.app.ActivityThread.main(ActivityThread.java:4363)
11-25 13:33:00.868 E/AndroidRuntime(1897)at java.lang.reflect.Method.invokeNative(Native Method)
11-25 13:33:00.868 E/AndroidRuntime(1897)at java.lang.reflect.Method.invoke(Method.java:521)
11-25 13:33:00.868 E/AndroidRuntime(1897)at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
11-25 13:33:00.868 E/AndroidRuntime(1897)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
11-25 13:33:00.868 E/AndroidRuntime(1897)at dalvik.system.NativeStart.main(Native Method)

Full log:
https://www.dropbox.com/s/4mdkioc8ik9fuec/asi_logs-20121125-133315.log

**Comment by eneq123** [comment]
New Nook come with pre-installed 1.2.0.

**Comment by eneq123** [comment]
Maybe this will be helpful: patch for fast page refresh for CoolReader by klush  (firmware 1.2.0)
http://4pda.ru/forum/index.php?s=&showtopic=191747&view=findpost&p=17333779

Brief review:
1. EpdController -> EpdRegionParams

```
    -                               Class clEpdControllerWave       = Class.forName("android.hardware.EpdController$Wave");
    +                               Class clEpdControllerWave;
    +                               if (DeviceInfo.EINK_NOOK_120)
    +                                       clEpdControllerWave = Class.forName("android.hardware.EpdRegionParams$Wave");
    +                               else
    +                                       clEpdControllerWave = Class.forName("android.hardware.EpdController$Wave");
__
    -                               Class clEpdControllerRegionParams = Class.forName("android.hardware.EpdController$RegionParams");
    +                               Class clEpdControllerRegionParams;
    +                               if (DeviceInfo.EINK_NOOK_120)
    +                                       clEpdControllerRegionParams = Class.forName("android.hardware.EpdRegionParams");
    +                               else
    +                                       clEpdControllerRegionParams = Class.forName("android.hardware.EpdController$RegionParams");
```
1. and non static setRegion:

```
-import android.view.View;
+import android.app.Activity;
-----
+       private static Constructor EpdControllerConstructors[] = null;
+       public static Activity n2MainActivity =  null;
+       private static Object mEpdController = null;
------
+                               if (DeviceInfo.EINK_NOOK_120) 
+                                       EpdControllerConstructors = clEpdController.getConstructors();
------
+                               if (DeviceInfo.EINK_NOOK_120 && mEpdController == null)
+                                       mEpdController = EpdControllerConstructors[0].newInstance(new Object[] { n2MainActivity });
                                Object regionParams =  RegionParamsConstructor.newInstance(new Object[] { 0, 0, 600, 800, enumsWave[wave]});
-                               mtSetRegion.invoke(null, "CoolReader", enumsRegion[region], regionParams, enumsMode[mode]);
+                               mtSetRegion.invoke(mEpdController, "CoolReader", enumsRegion[region], regionParams, enumsMode[mode]);
```

**Comment by marcelogp** [comment]
This is probably useful indeed, since it seems that B&N changed the low level EpdController class. However, I could not download the attachment from the post you linked. If you have it, please upload.

**Comment by eneq123** [comment]
https://www.dropbox.com/s/9ldwsgrz10zwbc1/nook120.patch

**Comment by marcelogp** [comment]
Please try with this test version (untested because I'm not using 1.2.0) and report back.

https://github.com/marspeople/NoRefreshToggle/downloads

EDIT: If the first doesn't work, try with the other one.

**Comment by eneq123** [comment]
NoRefreshToggle-debug.apk - crashes on 'tap to start" checkbox
NoRefreshToggle-debug2.apk - works well

Thank you very much

**Comment by marcelogp** [comment]
Good to hear. I will keep "NoRefreshToggle-debug2.apk" available from Downloads which is for 1.2.0 only, since it is not very straightforward to create a hybrid version.
